spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_mcms?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    filters: wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource